### PR TITLE
Create Can I help you?

### PR DESCRIPTION
**Pull request by TechnoBlade5**
Don't actually create this file

### CODE REVIEW

**Comment by Jude-Gideon** [comment]
Can you write a script to add tokens real quick? I need to see if you can actually make stuff.

**Comment by TechnoBlade5** [comment]
bet

**Comment by TechnoBlade5** [comment]
Don't you already have one?

**Comment by Jude-Gideon** [comment]
Yes, just trying to see what you can do.

**Comment by TechnoBlade5** [comment]
Ok
Give me some time (about a week or two)
I'm a kinda slow worker

**Comment by Jude-Gideon** [comment]
ok.

**Comment by Jude-Gideon** [comment]
im going to close this now, contact me on discord https://discord.gg/aeDraxAUpB

**Comment by Jude-Gideon** [comment]
or jude#8011

**Pull request closed without merging**
